version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
    ports:
      - 27017:27017
   mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: your_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: your_password
      ME_CONFIG_MONGODB_URL: mongodb://your_username:your_password@mongo:27017/
